language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "gem install foreman"
  - "sudo apt-get install -y libevent-dev python-gevent"
install:
  "pip install -r requirements.txt --use-mirrors"
# command to run tests
before_script: "python manage.py syncdb"
script: ./TEST
